### ISSUE TITLE
Disable lazy load feature  of extension

### ISSUE THREAD

**Issue by julianne49** [yireo/Yireo_Webp2#131] opened 2022-08-21 18:34 UTC
Hello & thank you for the extension. My site is using a theme that allows  all images to be lazy loaded & an option for lazy loading to be disabled on the LCP image. When enabling the Webp extension, it over rides the themes' lazy load feature & causes the LCP image to be lazy loaded. This is whether I change the settings to use/not use the theme's lazy load or the extension's lazy load. So, I was wondering is there anyway to keep the extension from lazy loading the LCP image? (Page speed Insights doesn't like the LCP image being lazy loaded)

Thank you.

**Comment by ppeyman** [comment] 2022-12-04 17:05
> Hello & thank you for the extension. My site is using a theme that allows all images to be lazy loaded & an option for lazy loading to be disabled on the LCP image. When enabling the Webp extension, it over rides the themes' lazy load feature & causes the LCP image to be lazy loaded. This is whether I change the settings to use/not use the theme's lazy load or the extension's lazy load. So, I was wondering is there anyway to keep the extension from lazy loading the LCP image? (Page speed Insights doesn't like the LCP image being lazy loaded)
> 
> Thank you.

You can go to` configuration > Yireo NextGenereationImage > Add lazy loading attribute` turn it To **No**

**Comment by julianne49** [comment] 2022-12-04 18:21
Thank you for trying to help. But, even when the "Add lazy loading attribute" is turned to No it still lazy loads the LCP image. The extension is lazy loading images whether or not the "Add lazy loading attribute" is set to No or Yes. I had to remove it from my site. 

However, thanks again for trying to help.

**Comment by jissereitsma** [comment] 2022-12-04 18:28
Please note that our extension is **not** lazy loading anything. It only adds the `lazy` flag if the configuration value for it is enabled. Also, in all our tests, the flag is not added by our extension when the configuration value is disabled. So I'm pretty sure that the issue you are describing is not due to the configuration value of our extension, because you mentioned that the configuration value is turned off.

Next, it is nice to explain that our extension will **not** do any lazy loading. It will enable a flag when instructed to do so. However, your browser could be lazy loading things anyway. And there might be various reasons why your browser is doing this: Perhaps another (!) extension is adding lazy loading by adding a flag, or perhaps by adding JavaScript, or perhaps a browser extension is causing this, or perhaps another reason.

Because none of this was reported, plus the extension was blamed on the first encounter, I'm pretty sure it is pointless to troubleshoot this. The problem is already gone (because you uninstalled the extension), no one else reported the same issue, and none of our tests confirm that our extension could be causing this. 

I'm closing this ticket because of the unneeded nature. If the extension is proven to have a bug after all, feel free to reopen this ticket or open another ticket.

**Closed by jissereitsma** 2022-12-04 18:28 UTC

**Comment by julianne49** [comment] 2022-12-04 18:42
Please don't be offended that I said the extension was causing the problem. When I had it installed that is what was happening. I did report it here in August hoping for some help & no one responded. Which is why I removed it from the site. I really wanted to use the extension & appreciate your time & work.

**Comment by jissereitsma** [comment] 2022-12-05 09:44
No worries. I'm not offended, but I'm trying to be strict. When an issue is reported, it doesn't mean a bug is there but it means that further troubleshooting was needed.
