### ISSUE TITLE
webp image not supporting with mobile image of page builder

### ISSUE THREAD

**Issue by sunilit42** [yireo/Yireo_Webp2#123] opened 2022-06-29 08:35 UTC
As pagebuilder generating image tag near by that create issue with page builder with mobile image

Mobile image is not converted into webp

Actual solution : it should be convert into webp image

**Comment by jissereitsma** [comment] 2022-07-06 08:56
Possible duplicate of https://github.com/yireo/Yireo_Webp2/issues/107

**Closed** 2022-07-06 10:28 UTC
