### ISSUE TITLE
Image not found exception

### ISSUE THREAD

**Issue by rakibabu** [yireo/Yireo_Webp2#5] opened 2019-06-06 14:20 UTC
Hi Yireo,

Thanks for this awesome module, still there is one problem I think. When an image is not found the Image/Convertor.php method needsConversion throws an exception.

In magento when an image is not found the default placeholder is shown. Can you fix this, when an image needs conversion but is not found it always returns to it default behavior?

Regards,

Raki

**Comment by jissereitsma** [comment] 2019-06-08 10:29
Hi @rakibabu thanks for your feedback. Let's debate this a little bit, so that I understand the issue better. The extension mainly reacts to HTML output and then trying to convert the `img` tags in that output to WebP images. If the original image is not there in the first place, the extension will simply skip that image anyway (https://github.com/yireo/Yireo_Webp2/blob/master/Plugin/ReplaceTags.php#L105). In my tests, this worked out fine for products that had missing images (so the placeholder was shown). Could you share some more details on where an exception was thrown?

**Comment by rakibabu** [comment] 2019-08-01 13:35
Hi @jissereitsma ,

Thanks for thinking this through and sorry for the late response. I think the issue is not really with product images but with other images replaced with the regex. This is not default magento but is there a possibility to fix this with placeholders?

Thanks

Raki

**Comment by jissereitsma** [comment] 2019-08-01 14:02
Thanks. But I can't reproduce an issue and you are referring to placeholders that are working in a general environment perfectly fine. So if there is something specific, please help me understand what that specific thing is. As of yet, you seem to be reporting a bug, that I can't produce so can't fix either.

**Comment by jissereitsma** [comment] 2020-02-04 04:34
I'm closing this issue for now. Feel free to re-open if you think this issue still applies.

**Closed by jissereitsma** 2020-02-04 04:34 UTC
