### ISSUE TITLE
Slider images not being converted

### ISSUE THREAD

**Issue by andremc420** [yireo/Yireo_Webp2#135] opened 2022-09-24 03:22 UTC
Hello again,

I'm using [Ox Slider](https://marketplace.magento.com/ox-multislider.html), and for some reason the banner slider images are not being converted and still being served as the original jpeg. I turned on logs but couldn't find anything related to this. 

I contacted their support, but couldn't quite understand what they mean:

>> There may be a new path created for our module by Webp converter developers for this to work properly. We had a similar experience with one of our customers in the past which got sorted after a new path was created by the other module's developers.

>> Please let us know if you still face any issues even after getting in touch with Webp converter's support team.

The images are stored in /pub/media/ox/heroslider/

Sorry if this has been asked before, I could not find a related issue. 

Any help is appreciated. Thanks for this great module!

**Comment by jissereitsma** [comment] 2022-09-24 07:26
The comment of `path` doesn't make sense and is not showing any analysis of the problem, it is only a wild guess to send you back.

Could it be that their module is already adding `picture` tags? See https://github.com/yireo/Yireo_Webp2/issues/100

**Comment by andremc420** [comment] 2022-09-24 16:50
Yes, I think that's it:

` <div class="oxmultislider image-slider-<?= $escaper->escapeHtmlAttr($block->getIdentifier()) ?>"
             id="home-slider">
            <?php foreach ($images as $image): ?>
                <div>
                    <div class="banner-wrapper">
                        <picture>
                            <source
                                media=
                                "(min-width: 1px) and (max-width: <?=
                                $escaper->escapeHtml($block->getSmallImageBreakpoint()) ?>px)"
                                srcset=
                                "<?= $escaper->escapeHtml($block->helperData->getMediaUrl()) . 'ox/heroslider/small/' .
                                $escaper->escapeHtml($image->getSmallImage()) ?>">`

I tried closing the source tags in that code like suggested, but the issue remains.

**Comment by jissereitsma** [comment] 2022-09-24 18:19
If the issue is indeed that a `picture` tag already exists, then this is simply a duplicate issue, because issue #100 explains all already. This is still pending work, but because it is duplicate, I'll close this issue. No need to try thing, existing picture tags are not supported as of yet.

**Closed by jissereitsma** 2022-09-24 18:19 UTC
