### ISSUE TITLE
Exception #0 (Yireo\NextGenImages\Exception\ConvertorException): WebP URL

### ISSUE THREAD

**Issue by Garde85** [yireo/Yireo_Webp2#65] opened 2021-02-12 10:40 UTC
Magento2.3.5-p2 
php7.2.34
NextGen 0.0.6
Webp2 0.10.1

When I visit product page, this is broken and this Exception is printed:

<pre>
1 exception(s):
Exception #0 (Yireo\NextGenImages\Exception\ConvertorException): WebP URL "https://local.test.it/media/catalog/product/cache/859c4163f610388a68847891a7214ffb/t/t/test-test.webp" does not exist

Exception #0 (Yireo\NextGenImages\Exception\ConvertorException): WebP URL "https://local.test.it/media/catalog/product/cache/859c4163f610388a68847891a7214ffb/t/t/test-test.webp" does not exist
#1 Yireo\Webp2\Plugin\AddWebpToGalleryImagesJson->getWebpUrl() called at [vendor/yireo/magento2-webp2/Plugin/AddWebpToGalleryImagesJson.php:57]
#2 Yireo\Webp2\Plugin\AddWebpToGalleryImagesJson->appendImages() called at [vendor/yireo/magento2-webp2/Plugin/AddWebpToGalleryImagesJson.php:44]
#3 Yireo\Webp2\Plugin\AddWebpToGalleryImagesJson->afterGetGalleryImagesJson() called at [vendor/magento/framework/Interception/Interceptor.php:146]
#4 Magento\Catalog\Block\Product\View\Gallery\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#5 Magento\Catalog\Block\Product\View\Gallery\Interceptor->___callPlugins() called at [generated/code/Magento/Catalog/Block/Product/View/Gallery/Interceptor.php:65]
#6 Magento\Catalog\Block\Product\View\Gallery\Interceptor->getGalleryImagesJson() called at [vendor/magento/module-catalog/view/frontend/templates/product/view/gallery.phtml:45]
#7 include() called at [vendor/magento/framework/View/TemplateEngine/Php.php:59]
#8 Magento\Framework\View\TemplateEngine\Php->render() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#9 Magento\Framework\View\TemplateEngine\Php\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#10 Magento\Framework\View\TemplateEngine\Php\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#11 Magento\Framework\View\TemplateEngine\Php\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/View/TemplateEngine/Php/Interceptor.php:26]
#12 Magento\Framework\View\TemplateEngine\Php\Interceptor->render() called at [vendor/magento/framework/View/Element/Template.php:271]
#13 Magento\Framework\View\Element\Template->fetchView() called at [generated/code/Magento/Catalog/Block/Product/View/Gallery/Interceptor.php:505]
#14 Magento\Catalog\Block\Product\View\Gallery\Interceptor->fetchView() called at [vendor/magento/framework/View/Element/Template.php:301]
#15 Magento\Framework\View\Element\Template->_toHtml() called at [vendor/magento/framework/View/Element/AbstractBlock.php:1100]
#16 Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}() called at [vendor/magento/framework/View/Element/AbstractBlock.php:1104]
#17 Magento\Framework\View\Element\AbstractBlock->_loadCache() called at [vendor/magento/framework/View/Element/AbstractBlock.php:674]
#18 Magento\Framework\View\Element\AbstractBlock->toHtml() called at [generated/code/Magento/Catalog/Block/Product/View/Gallery/Interceptor.php:830]
#19 Magento\Catalog\Block\Product\View\Gallery\Interceptor->toHtml() called at [vendor/magento/framework/View/Layout.php:566]
#20 Magento\Framework\View\Layout->_renderBlock() called at [vendor/magento/framework/View/Layout.php:542]
.....
</pre>

**Comment by AbdulSamadAbbasi** [comment] 2021-02-12 11:19
Did you check if the converted .webp image actually exists at that path?

**Comment by Garde85** [comment] 2021-02-12 12:31
The strange thing is that seems that if the module is activated, magento 
is not able to create product image in "cache" folder 
(pub/media/catalog/product/cache).
When your Yireo\Webp2\Convertor\Convertor class, calls this function:

     private function fileExists($filePath): bool
     {
         try {
             $fileRead = $this->fileReadFactory->create($filePath, 'file');
             return (bool)$fileRead->readAll();
         } catch (FileSystemException $fileSystemException) {
             return false;
         }
     }

always generate a FileSystemException.

To answer to your question: No image is not present.

This problems appens only on product page. In listing page images are 
generated in webp format.

If I disable both modules 
(yireo/magento2-webp,yireo/magento2-next-gen-images ) all works well.


Il 12/02/21 12:19, AbdulSamadAbbasi ha scritto:

**Comment by jissereitsma** [comment] 2021-02-12 15:52
I can't duplicate this issue myself. It almost seems as if some kind of customization of the gallery is made, to load images in a different order. In any case, it is preferable to have an exception not end up on the frontend, so release 0.10.2 is now offering a fix so that the original URL is simply returned.

**Comment by JosienV92** [comment] 2021-02-15 12:14
I had the same issue on M2.4.1, PHP7.3, Yireo_WebP2 0.10.0. For me, it was resolved when I updated the module to v0.10.3

**Comment by Garde85** [comment] 2021-02-15 12:21
> I had the same issue on M2.4.1, PHP7.3, Yireo_WebP2 0.10.0. For me, it was resolved when I updated the module to v0.10.3

I confirm that, with 0.10.3, this  problem has been fixed, but images in product page are not always converted in .webp format. 
Version 0.10.3 NOT generate the Exception, but not convert all images in product page.

**Comment by jissereitsma** [comment] 2021-02-15 12:48
@JosienV92 Thanks for mentioning.

@Garde85 Did you make sure to troubleshoot the exception mentioned earlier? In short, the extension works fine in every single environment that I have tested it in. The reason you encountered an exception was that something *exceptional* happened in your specific environment - permission issues, incorrect images, wrong bindings, I don't know. But it is important as a system integrator that you troubleshoot this. That's why those exceptions were there. The exceptions were hidden indeed, but this is now fixed with the latest release of both the WebP and the NextGenImages extension. Enable logging in the backend of NextGenImages and then study the log file `var/log/yireo_nextgenimages.log`. In my case, those logs stay empty - as intended. Any mentioning in those blogs refers to an error that you really don't want to go live with.

**Comment by Garde85** [comment] 2021-02-15 12:55
@jissereitsma thank you for your suggestions and your help. I will investigate about this error asap, and then I will write here to share my analysis.

**Comment by AbdulSamadAbbasi** [comment] 2021-02-16 04:21
@jissereitsma can you please clarify why would we have same plugin in  `(\Swatches\Helper\Data)` in both extensions, Webp2 and NextGen, when we are using them together? Talking about 0.10.4.

**Comment by AbdulSamadAbbasi** [comment] 2021-02-16 05:40
@Garde85 if you could please confirm swatches are updating not in gallery but product listing? See screenshot below, when I change colors, it doesn't bring respective item but load again same.
![swatchesissue](https://user-images.githubusercontent.com/38076752/108022960-6dab6180-7043-11eb-880e-71da7186ae0f.png)

**Comment by jissereitsma** [comment] 2021-02-16 07:04
I have the same issue. I can work on this voluntarily as soon as I have free time available. Feel free to investigate already.

**Comment by jissereitsma** [comment] 2021-02-16 07:06
This ticket is now duplicate and will be closed. If you are discussing this issue of the swatches on the category page, please refer to https://github.com/yireo/Yireo_Webp2/issues/62 Duplicating problems across multiple tickets does not help efficiency. I will therefore close this issue. Feel free to reopen if you have an issue related to the original exceptions discussed here.

**Closed by jissereitsma** 2021-02-16 07:06 UTC
