### ISSUE TITLE
Not converting product page product images to webp

### ISSUE THREAD

**Issue by surao101** [yireo/Yireo_Webp2#42] opened 2020-07-23 09:57 UTC
Testing with the following

- Chrome Version 84.0.4147.89 (Official Build) (64-bit)
- Magento version 2.3.5-p1
- PHP ver PHP 7.3.19
- Yireo WebP2 ver 0.7.2

1. Set to developer mode
2. Used composer to install, ran upgrade and enabled the extension
3. folders with pub/media/catalog/product set to 775
4. Flushed all cache including image cache, disabled FPC

On the category pages and CMS pages the images get converted to webp, the same image that gets converted to webp on a category page doesn't get converted to webp on the product page.

Category page example. - http://dev.koshmart.com/uk/reproductions/artists/claude-monet
Product page example. - http://dev.koshmart.com/uk/haystacks-meules-1890-claude-monet-painting-reproduction-cm0001

If you check the product images on the product page they still jpg whilst all the other images on the product page are webp.
The same product image on the category page is converted to webp.

I'm not sure why this is happening,  and how it can be fixed.

**Comment by jissereitsma** [comment] 2020-07-23 10:13
Thanks for this report. Are you sure that the WebP images are not being added to the HTML source of the product page? You say it is not working, but if I'm checking the HTML source myself (for http://dev.koshmart.com/eu/haystacks-meules-1890-claude-monet-painting-reproduction-cm0001) I'm seeing WebP images all over the place.

Are you sure this is a problem with this extension? Or are you confused about the image gallery effect, reloading the original JPEG images on top of the WebP images? If you want to optimize the product page, start with replacing the outdated Fotorama effect. 

To quote https://github.com/yireo/Yireo_Webp2/blob/master/USAGE.md: "The Fotorama gallery of the Magento core product pages is replaced with WebP images without issues as well. However, the Fotorama effect loads new JPG images again, replacing the original <picture> tag. This shows that the Fotorama library is not scalable and may be a bad decision to use. We recommend you replace it with the Notorama module instead."

**Comment by surao101** [comment] 2020-07-23 10:28
Yes almost all the images on the product page convert to webp as I'd stated the initial report. 

It's only the product image within fotorama that doesn't convert. Inspect element for the product image shows it's still jpg, so is this what you mean by "reloading the original JPEG images on top of the WebP images"? 

```
<div class="fotorama__stage__frame fotorama__fade-rear fotorama__active fotorama_horizontal_ratio fotorama__loaded fotorama__loaded--img" aria-hidden="false" data-active="true" href="http://dev.koshmart.com/pub/media/catalog/product/cache/b5cd64b7df4564c7d7ddac4ccac7655c/c/m/cm0001-haystacks-meules-1890-by-claude-monet.jpg" style="left: 0px; transition-duration: 0ms; opacity: 1;"><img src="http://dev.koshmart.com/pub/media/catalog/product/cache/b5cd64b7df4564c7d7ddac4ccac7655c/c/m/cm0001-haystacks-meules-1890-by-claude-monet.jpg" alt="Haystacks (Meules) 1890 by Claude Monet" aria-labelledby="labelledby1595498218315" class="fotorama__img" aria-hidden="false"><div class="fotorama__caption" aria-hidden="true">
    <div class="fotorama__caption__wrap" id="labelledby1595498218315">Haystacks (Meules) 1890 by Claude Monet</div>
</div></div>
```
Checking the folder where the product image is located shows only the jpg file, if it was converted should there not be a webp version of the jpg file.

Does replacing the outdated Fotorama effect entail installing this module (notorama) [https://github.com/robaimes/module-notorama](https://github.com/robaimes/module-notorama)?

**Comment by jissereitsma** [comment] 2020-07-23 10:46
Yes, "reloading the original JPEG images on top of the WebP images" means that you can confirm yourself in the HTML source (which is not the inspect element preview of the live DOM) that all WebP images are there. That's what this extension does. Next, the image gallery of Fotorama replaces the original DOM with a new DOM (which is what the inspect element preview shows). In short, you are pointing out a shortcoming with Fotorama, and unfortunately, as a volunteer of adding WebP images to Magento using this free extension, I'm not able to volunteer in fixing issues with Fotorama itself. Fotorama is no longer active, bad for SEO, bad for performance and strongly outdated. Hence the docs are trying to make it clear that using Fotorama is causing you other issues, while you are only focusing on the WebP part now. I would recommend you to fix the other issues first, and then look back to see if WebP is better supported. I'm not saying how you can fix everything. But the docs are pretty clear in the options that you have, I guess. I'll close this issue because it was documented in the docs already.

**Closed by jissereitsma** 2020-07-23 10:46 UTC
