### ISSUE TITLE
PDP gallery images aren't swapping to WebP

### ISSUE THREAD

**Issue by PatrickWhitehouse** [yireo/Yireo_Webp2#155] opened 2023-09-18 16:19 UTC
Hi there,

We're experiencing some issues with the extension on PDP pages, more specifically the gallery area. 

The gallery images do not seem to be swapped for the WebP variation. **The WebP images are being generated** as I'm able to navigate to these in the browser. 

We are using Hyva, and have tried with and without the compatibility module in place. 

We have also set the theme back to Hyva default to rule out any template changes in our theme affecting this. 

I have spoken with a few people in the Hyva slack channel who are also experiencing this same issue. https://hyva-themes.slack.com/archives/C01L7RY28G5/p1694091951257419

Magento version: 2.4.4
PHP Verion: 8.1.21
WebP2 Version: 0.13.1
NextGenImages Version: 0.4.1
Url where the extension doesn't work: https://staging.petertyson.co.uk/kudos-titan-505
Url where the extension is working: https://staging.petertyson.co.uk/speakerssubs/hifi-speakers/bookshelf

Thanks :)

**Comment by jissereitsma** [comment] 2023-09-22 10:30
This was still a pending issue, where the gallery lacked flexibility to be extended in such a way. A new release of NextGenImages (0.5.0)  and Webp (0.13.3) will be released later today to add a possible fix. I'm closing this issue as of yet. Feel free to reopen this issue if the problem is there after upgrading.

**Closed by jissereitsma** 2023-09-22 10:30 UTC
