### ISSUE TITLE
Images are not converted to webp

### ISSUE THREAD

**Issue by mtjweb** [yireo/Yireo_Webp2#41] opened 2020-06-30 15:25 UTC
Magento 2.3.5-p1
PHP 7.2.31
Module 0.7.2

I installed te module with composer. The module is enabled and I checked the file permissions. All were ok.

The website is still showing the images in the original format.

**Comment by jissereitsma** [comment] 2020-06-30 15:33
Thanks for reporting this. Could you complete the following as well? https://github.com/yireo/Yireo_Webp2/blob/master/SUPPORT.md

**Comment by mtjweb** [comment] 2020-06-30 15:50
What browser did you test this with? Firefox 77.0.1 64-bit
What is your Magento version? 2.3.5-p1
What is your PHP version? 7.2.31
Which version of the WebP extension did you install? 0.7.2
How did you install this module? composer require yireo/magento2-webp2
What did you do to enable the module? php bin/magento module:enable Yireo_Webp2
Have you tested this after flushing all caches? Yes
Have you tested this after disabling all caches, especially the Full Page Cache? Yes
Are you testing this in the Developer Mode or in the Production Mode? Developer Mode
Under Stores > Configuration > Yireo > Yireo WebP2, what settings do you see?
        Value of Enabled     Yes
        Value of Debug log    No
        Value of GD support   WebP is supported by GD 
        Value of PHP version    7.2.31
        Value of Module version    0.7.2
Could you supply a URL to a live demo? https://mtjshop.nl
Could you please supply a snapshot of the HTML source of a product page? Not sure what you mean, you can check the code at the link provided.

**Comment by jissereitsma** [comment] 2020-06-30 16:00
Thanks. 

I can see the following HTML segment on your homepage:
```html

<picture>
  <source type="image/webp" srcset="https://mtjshop.nl/pub/media/logo/default/Logo-Wit500x73_1.webp">
  <source type="image/png" srcset="https://mtjshop.nl/pub/media/logo/default/Logo-Wit500x73_1.png">
  <img src="https://mtjshop.nl/pub/media/logo/default/Logo-Wit500x73_1.png"
  title="MTJshop.nl"
  alt="MTJshop.nl"
  width="500"            height="73"     loading="lazy" /></picture>
```

This actually shows that our WebP extension is working perfectly fine. Our extension generates a picture element, so that it is up to the browser to use the right image. If Firefox is not, that's out of my hands. Following this page https://caniuse.com/#feat=webp your Firefox instance should support it.

What makes you say that it is not working in your browser? How did you conclude this?

**Comment by mtjweb** [comment] 2020-06-30 16:42
You are right, it's working on the images on the homepage. But when I check the product images at the productpage, I don't see the source tags.

It is strange that the wepb-format isn't preferred above the png format. I also checked in Google Chrome and Chrome also preferred the png format above webp.

**Comment by jissereitsma** [comment] 2020-06-30 18:03
Are we referring to the same site? Because the HTML of your product pages again shows the same `picture` sets as I mentioned for your homepage. Please note that Fotorama is outdated, bad for performance and not extensible. So if you worry about optimizing your product pages, get rid of Fotorama is a step one - not a step related to this extension.

What makes you say that it is not working in your browser? How did you conclude this?

I'm going to close this ticket now, because you are either using the wrong testing method or you are drawing wrong conclusions. On both the product page and the homepage, I found the extension to be working and in my browser, WebP images are loading. Because you have not answered back on the mechanism that you are using to conclude that there is an issue, I'm assuming the problem is that mechanism and not this extension.

**Closed by jissereitsma** 2020-06-30 18:03 UTC

**Comment by mtjweb** [comment] 2020-06-30 18:34
We are referring to the same site.

You can just say that you like me to use Notorama instead of Fotorama (Found your answer while Googling). Normally I do not expect to change other modules to get a new module working. At least I know you also saw the problem what I tried to tell you.

When I use is the inspector of the browsers. I can see that the module is not working for the productimages on the productpage (Fotorama problem). And for the other images I can see my browser does not prefer the webp format. I also checked this on a just newly installed pc.

Please do not tell me that you asume that I'm using the wrong testing method and drawing wrong conclusions. It is not nice.

You build a great module and I just want it to work as well as possible.

Tomorrow I will check the Notorama module.

**Comment by jissereitsma** [comment] 2020-06-30 18:41
No, that's not an accurate assumption. The WebP2 extension successfully replaces the JPEG images with the WebP equivalents. By monitoring your traffic, you can see this for yourself. So that closes this ticket. However, there is a known issue with Fotorama (please note this extension, but the Fotorama JavaScript effect on its own) that causes all images to load twice. Fix that issue in Fotorama and any other image optimization makes sense, including this WebP solution. Unfortunately, Fotorama has been abandoned for years. The issue is not with this extension, it is with your expectations that this extension is able to fix additional issues within Fotorama. 

I don't recommend other solutions perse, I simply want people to reckognize that there is no performance measure that fixes all issues. People then think Fotorama is great because it is part of Magento 2. It is not. And Magento engineers know this. The story is simply more complex because backwards compatibility policies and Adobes future.

Using the inspector in the browser only gives you one narrow look at what is going on. The network traffic is another analysis. The HTML source yet another one. The total story is that a product page using Fotorama without WebP is bad for performance. And a product page using Fotorama with WebP is still bad for performance. Don't shoot the messenger.

**Comment by mtjweb** [comment] 2020-06-30 18:57
It is what you're saying on this page:
https://www.yireo.com/software/magento-extensions/webp2

I didn't shoot the messenger, just the one who attacked me. ;)

Don't be offended. Tomorrow I will see what I am going to do with Fotorama. And as you indicated, Fotorama is standard in Magento and it is not surprising that this problem pops up. Just mention the problem with Fotorama, not everybody knows this.

**Comment by jesperingels** [comment] 2023-07-18 11:42
Hi, 
Notorama is now deprecated -> https://github.com/robaimes/module-notorama 
Does anyone know an alternative for this? To fix the issue with fotorama causing the webp image to not load.

**Comment by jissereitsma** [comment] 2023-09-22 10:27
I think that the fact that Notorama is no longer maintained by Rob, does not necessarily mean that it does not work. Perhaps somebody could simply clone it and make it work again?

Anyway, in Fotorama, in our cases, things are working. If they are not, perhaps it is a specific issue, which would be best picked up with opening a GitHub Issue here.
